[package]
name = "fren"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
crossterm = "0.29.0"
dirs = "6.0.0"
image = { version = "0.25.9", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
lru = "0.16.3"
natord = "1.0.9"
ratatui = "0.30.0"
ratatui-image = "10.0.5"
unicode-width = "0.2.2"
